name: 'tap_solarvista'
version: '0.0.1'

config-version: 2

profile: local

source-paths: ["models"]   # paths with source code to compile
analysis-paths: ["analysis"] # path with analysis files which are compiled, but not run
target-path: "target"      # path for compiled code
clean-targets: ["target"]  # directories removed by the clean task
test-paths: ["tests"]       # where to store test results
data-paths: ["data"]       # load CSVs from this directory with `dbt seed`
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  tap_solarvista:
    base:
      materialized: table
    transform:
      materialized: table
      
vars:
  schema: "{{ env_var('TARGET_POSTGRES_SCHEMA') }}"              # the schema where the raw Solarvista tables are located
