-- Assert that all these columns exist in vw_project_sla
-- These are the currently specific columns used by a meltano report
-- The where causes the select to still run but return nothing
-- So if it can't select a column it still returns an error
select
    vw_project_sla.project_id,
    vw_project_sla.report_year,
    vw_project_sla.report_month,
    vw_project_sla.report_day,
    vw_project_sla.day_of_month,
    vw_project_sla.day_of_year,
    vw_project_sla.day_of_week,
    vw_project_sla.day_of_week_name,
    vw_project_sla.week_key,
    vw_project_sla.week_of_year,
    vw_project_sla.territory_id,
    vw_project_sla.territory_name,
    vw_project_sla.site_id,
    vw_project_sla.site_name,
    vw_project_sla.customer_id,
    vw_project_sla.customer_name,
    vw_project_sla.problemtype,
    vw_project_sla.schedule_start_date,
    vw_project_sla.appliedresponsesla,
    vw_project_sla.responsedue_date,
    vw_project_sla.appliedfixsla,
    vw_project_sla.fixdue_date,
    vw_project_sla.createdon,
    vw_project_sla.cancelled_timestamp,
    vw_project_sla.closedon,
    vw_project_sla.remoteclosed_timestamp,
    vw_project_sla.reactivated_timestamp,
    vw_project_sla.first_response,
    vw_project_sla.final_fix,
    vw_project_sla.source,
    vw_project_sla.total_projects,
    vw_project_sla.total_workitems,
    vw_project_sla.is_open,
    vw_project_sla.is_closed,
    vw_project_sla.is_refix,
    vw_project_sla.is_firstfix,
    vw_project_sla.response_within_sla,
    vw_project_sla.final_fix_hours,
    vw_project_sla.final_fix_within_sla,
    vw_project_sla.final_fix_missed_sla
from {{ ref('vw_project_sla')}}
where vw_project_sla.project_id = null
